version: '2'
services:
  app:
    build:
      context: .
      args:
        app_env: development
    volumes:
      - .:/usr/local/app
      - ./public:/usr/local/app/public
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      REDIS_URL: redis://redis:6379/0
    ports:
      - "3000:3000"
    links:
      - postgres
      - mailcatcher
      # - redis
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
  # worker:
  #   extends:
  #     file: base-compose.yml
  #     service: app
  #   command: [bundle, exec, sidekiq, -C, config/sidekiq.yml]
  #   links:
  #     - postgres
  #     - redis
  #     - mailcatcher
  # redis:
  #   image: redis:3.2
  #   volumes:
  #     - redis-data:/data
volumes:
  postgres-data: {}
  redis-data: {}
